#!/usr/bin/env bash

set -o errexit

DOMAIN=${1:-magento.test}
VERSION=${2:-2.4.6}

curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash

# &&'s are used below otherwise onelinesetup script fails/errors after bin/download
bin/download "${VERSION}" \
  && bin/setup "${DOMAIN}"
