name: 'ShellCheck'

on:
  push:
    paths:
    - 'compose/bin/**'
    branches:
    - "master"

  pull_request:
    paths:
    - 'compose/bin/**'

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      id: check
      env:
        SHELLCHECK_OPTS: -o add-default-case,avoid-nullary-conditions,check-set-e-suppressed,check-unassigned-uppercase,quote-safe-variables,require-double-brackets,require-variable-braces -P compose/bin -P compose/env -x
      with:
        check_together: true
        scandir: './compose/bin'
